/**
 * Created by wenbo.kuang on 2018/6/7.
 */
export const GET_ARTICLE = 'DETAIL/GET_ARTICLE';
export const GET_ARTICLE_SUCCEED = 'DETAIL/GET_ARTICLE_SUCCEED';
export const GET_ARTICLE_ERROR = 'DETAIL/GET_ARTICLE_ERROR';
export const GET_ARTICLE_FAILED = 'DETAIL/GET_ARTICLE_FAILED';