/**
 * Created by wenbo.kuang on 2018/5/30.
 */
export const GET_MESSAGE = 'HOME/GET_MESSAGE';
export const GET_MESSAGE_SUCCEED = 'HOME/GET_MESSAGE_SUCCEED';
export const GET_MESSAGE_FAILED = 'HOME/GET_MESSAGE_FAILED';
export const GET_MESSAGE_ERROR = 'HOME/GET_MESSAGE_ERROR';