/**
 * Created by wenbo.kuang on 2018/6/7.
 */
export const ARTICLE_SAVE = 'EDITOR/ARTICLE_SAVE';
export const ARTICLE_SAVE_SUCCEED = 'EDITOR/ARTICLE_SAVE_SUCCEED';
export const ARTICLE_SAVE_ERROR = 'EDITOR/ARTICLE_SAVE_ERROR';
export const ARTICLE_SAVE_FAILED = 'EDITOR/ARTICLE_SAVE_FAILED';